[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 200
enableXsrfProtection = false
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
